### PR TITLE
Add cli tool for token generation

### PR DESCRIPTION
**Pull request by mhallendal**
@TheGrandmother @dmarell

### CODE REVIEW

**Comment by TheGrandmother** [comment]
@mhallendal 
```
+node tools/generate-token.js <path-to-private-key.json>
```
The `path-to-private-key.json` is not rellative to the path where the command was executed from.
So if im on the root dir of the project running it will return a file not found to the path i gave:
```
+grandmother:basic-jwt-auth$ node tools/create-token.js ../tir-slack/key.json                                                                                                                                                                   
module.js:529                                                                                                                                                                                                                                                                                       
    throw err;                                                                                                                                                                                                                                                                                      
    ^                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                    
Error: Cannot find module '../tir-slack/caglabs-6fe585070bf6.json'                                                                                                                                                                                                                                  
    at Function.Module._resolveFilename (module.js:527:15)                                                                                                                                                                                                                                          
    at Function.Module._load (module.js:476:23)                                                                                                                                                                                                                                                     
    at Module.require (module.js:568:17)                                                                                                                                                                                                                                                            
    at require (internal/module.js:11:18)                                                                                                                                                                                                                                                           
    at Command.<anonymous> (/home/grandmother/CAG/basic-jwt-auth/tools/create-token.js:9:17)                                                                                                                                                                                                        
    at Command.listener (/home/grandmother/CAG/basic-jwt-auth/node_modules/commander/index.js:300:8)                                                                                                                                                                                                
    at emitOne (events.js:115:13)                                                                                                                                                                                                                                                                   
    at Command.emit (events.js:210:7)                                                                                                                                                                                                                                                               
    at Command.parseArgs (/home/grandmother/CAG/basic-jwt-auth/node_modules/commander/index.js:637:12)                                                                                                                                                                                              
    at Command.parse (/home/grandmother/CAG/basic-jwt-auth/node_modules/commander/index.js:457:21)
                                                                                                                                                                                                  
+grandmother:basic-jwt-auth<add-cli-tool-for-token-generation>$ cat ../tir-slack/key.json
// STUFF //  
```

**Comment by TheGrandmother** [comment]
Besides that I tested it and it works.

**Comment by mhallendal** [comment]
Good catch, should be fixed now.

**Comment by TheGrandmother** [comment]
Legendary fix!
I'm cool with merging this.

**Pull request merged**
